product:
  name: "SaaStack"
  tagline: "From code to customer in days, not months."
  key_claims:
    - "Production-ready SaaS infra templates"
    - "Auth, payments, observability, CI/CD prewired"
    - "Opinionated defaults; easy to extend"
  proof_points:
    - "Teams rebuilt on SaaStack shipped faster with fewer incidents"
    - "Best-practice patterns helped scale squads cleanly"
  links:
    docs: "https://example.com/docs"
    github: "https://github.com/your-org/your-repo"
    demo: "https://example.com/demo"

target_personas: [developer, technical_cofounder]

keywords:
  include:
    - "vibe coding"
    - "SaaS boilerplate"
    - "replacing engineers"
    - "replacing juniors"
    - "time to market"
    - "ai tooling"
    - "founders trying to vibe code"
    - "productionize"
    - "product to market"
    - "start ups"
    - "scalability"
    - "observability"
  exclude:
    - "airdrop"
    - "MLM"

guardrails:
  avoid_phrases: ["10x overnight", "revolutionize", "disrupt"]
  tone: "no hype, concrete examples, code-first"

autopost:
  enabled: false
  reddit:
    allowed_subreddits: ["programming","devops","selfhosted","saas","startups"]
    min_score: 10
